### ISSUE TITLE
Undeleting a line causes the editor to fill with the undeleted line and then crash (3.9.6)

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#63]
Deleting a line (RAmiga + D) and then Undeleting it (RAmiga + U) causes the editor to be flooded with the undeleted line, and then causes a complete system crash.

**Comment by honitos** [comment]
fixed with next version

**Comment by daedalus2097** [comment]
Thanks :) Unfortunately, while the flood of undeleted lines doesn't happen any more, it still crashes for me when I try to undelete a line...
